#ifndef BONE_RUNTIME_KEYWORD_H
#define BONE_RUNTIME_KEYWORD_H

#define BN_KWD_FUNCCALL ("opCall")
#define BN_KWD_POSITIVE ("opPositive")
#define BN_KWD_NEGATIVE ("opNegative")
#define BN_KWD_CHILDA ("opChilda")
#define BN_KWD_NOT ("opNot")
#define BN_KWD_PLUS ("opPlus")
#define BN_KWD_MINUS ("opMinus")
#define BN_KWD_MULTIPLY ("opMultiply")
#define BN_KWD_DIVIDE ("opDivide")
#define BN_KWD_MODULO ("opModulo")
#define BN_KWD_BIT_AND ("opBitAnd")
#define BN_KWD_BIT_OR ("opBitOr")
#define BN_KWD_EXC_OR ("opExcOr")
#define BN_KWD_LSHIFT ("opLeftShift")
#define BN_KWD_RSHIFT ("opRightShift")
#define BN_KWD_GT ("opGT")
#define BN_KWD_GE ("opGE")
#define BN_KWD_LT ("opLT")
#define BN_KWD_LE ("opLE")
#define BN_KWD_EQUAL ("opEqual")
#define BN_KWD_NOTEQUAL ("opNotEqual")
#endif